kind: pipeline
name: default

steps:
- name: build
  image: gradle:jdk11
  commands:
  - chmod +x gradlew
  - ./gradlew build

- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
