kind: pipeline
name: default

steps:
- name: fetch-tags
  image: drone/git
  commands:
  - git fetch --tags

- name: build
  image: androidsdk/android-31:latest
  commands:
  - ./gradlew assemble

- name: unit-tests
  image: androidsdk/android-31:latest
  commands:
  - ./gradlew check

- name: integration-tests
  image: androidsdk/android-31:latest
  commands:
  - ./gradlew connectedCheck

- name: code-analysis
  image: mailbyms/drone-sonar-plugin
  settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token
      java_binaries: target/classes
      # optional, for sonarqube webhook
      #custom_ding_token:
      #  from_secret: dingtalk_token
