kind: pipeline
name: default

steps:
- name: fetch
  image: drone/git
  commands:
  - git fetch --tags

- name: build
  image: gradle:jdk11
  commands:
  - gradle assemble

- name: unit-tests
  image: gradle:jdk11
  commands:
  - gradle check

- name: integration-tests
  image: gradle:jdk11
  commands:
  - gradle connectedCheck

- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
