kind: pipeline
name: default

steps:
- name: test
  image: gradle:jdk11
  commands:
  - gradle assemble
  - gradle check

- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
