language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-28.0.0-rc2
  - android-P
  - extra-android-m2repository
  - extra-android-support
  - extra-google-m2repository
  - extra-google-google_play_services
script:
- "./gradlew build connectedCheck"
before_install:
- chmod +x gradlew
- yes | sdkmanager "platforms;android-P"
