language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-24.0.2
  - android-24
  - extra-android-m2repository
  - extra-android-support
  - extra-google-m2repository
  - extra-google-google_play_services
script:
- "./gradlew build connectedCheck"
before_install:
- chmod +x gradlew
