sudo: required

language: android
jdk: oraclejdk8

env:
 global:
   - ANDROID_API=P
   - ANDROID_BUILD_TOOLS=28.0.0-rc2

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_install:
  # Travis still uses 'android' command behind the 'components' section update.
  # That command is obsolete and cannot update Android SDK Tools after 25.2.5.
  # Let's solve it here with the new command 'sdkmanager'
  - yes | sdkmanager --verbose "build-tools;${ANDROID_BUILD_TOOLS}"
  - yes | sdkmanager --verbose "platform-tools"
  - yes | sdkmanager --verbose "tools"
  - yes | sdkmanager --verbose "platforms;android-${ANDROID_API}"
  - yes | sdkmanager --verbose "extras;android;m2repository"

  # Check tools and dependencies installed
  - yes | sdkmanager --list

  - chmod +x gradlew

script :
  - ./gradlew build connectedCheck
