language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-24.0.2
  - android-24
  - extra-android-m2repository
  - extra-android-support
  - extra-google-m2repository
  - extra-google-google_play_services
script:
- "./gradlew build connectedCheck"
env:
  global:
    #SWAD_APP_KEY
  - secure: CBH/rpdOvSnmcG3oElpUVFXEFkV1tOnL7ZDAVQcVmb7Volhbp2xbzH98kBob3Zt7ZknlkZ4vzpEwHb11lUDZK8igMgsL/ZcORPURZ4549a1SJL8kG587QLcQ6SZA//7z1B6KraMaEC5jOaP2tA3B7uEmrhE+lXJLvDOPOjJxvQtCOBtIdOIR6TcugcA12XGgDl9cgsF8kvS0iTltJrKkhwpJtZAvHbmG+7sgKn8vwhv7gMYIHwMH+jfHT4Pd1VEhU0kjGNlHThOUWD2KQSZF4XGqwVpD+dT29aOXw74cAhlYo2xPvrs4a48fdJKktDXGZdvEqXNCXBLW7Di7WQyJLMUwjcgapVZSemPyCCWW9kWIle9K3Hb9c4JgjwjvdS5QLA+bNOSmMPYzUSRh/W/LyH/C7ft2z16dEPgpmOANg1rcgMTjtvGyZGVpNuWUq/bCBwKSYvy4EgEaE8E6zBAM92iNrDrJopIFctSISjYmGUazVROpvR62t85qS6bt/U9hkfHQOz/SI+ltrxkii2q4g3Vy4PqaTdGYgQCeYlXjIgrtuLwysWmJi04kLHd+uuRHGbm3jrAaHgeQxg8Gf9NFb5mK5Wgcjw0NnR82I2cWnaBs48IPzUALDLPE+xnepVZ9fHY2UL1+wCqZUxzA6IiAdxLgmKRjyxbJnHRHwgVShzI=
    #ANALYTICS_APP_KEY
  - secure: RSSmGmB+QshNkSLyWQe3YnzwCJSXtOX6foHeKsGlR1cJ40V9gQus4hSUTuS68xK738+c7+8/nNNibV0vMhR38+RAt5IIQSStvwBDKCDinFmKiz3SakCBd5NqGqRCekz+QeXZnCvwDK5xsnJXBOZ4gSVAIN5OQtX6+rQMXC1ydufzRXNM77V4pGG7wavf+4nqX0tDTzhf3RreV0sJGmBb2i/1CnRmgjwLwWqYLXqHWNanAtIPYnibhF2mFlgzd9Vnzkf3fZnRoBmQssjNhE/kv7r7uBF/1U5Y8PVSAqdgsd0NMc8QQDhZK8HKkBK/RRNwnPpD82bs8mWyaK62PM7fewTf5odViFxeA9qPw02RiCtHpAyBmIoxDKImXKimnr9/AAx3OrG0pW25b4AAi0SsyJl4px8TibsZwy3tDv9uGzKAvhCVG+fRMiWnQOnXXdw9+waIDgdk1ysj48ndtrXaEdcgGegOfzeya6OXfwsitwfynfvp29zbfNwQxhtVmUcF0rvOaGuNdGHaaGUOW5f3gToSrsbABVOpBcxcyzL6N9/tsOyJNZe5yiYqIEv89Qim2iHnOGMZDQiSHVtkpKqk1opWx5IqcBv1nt2a7pR0q3nYSwXaZpBoT05KJZ1yJsW+Sonebqfd2PO2Z0OgK6v0S7nuI3EoXP2gQ5qY4zk4iGo=
before_install:
- chmod +x gradlew
