language: android
jdk:
  - oraclejdk8
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-24.0.2
  - android-24
  - extra-android-m2repository
  - extra-google-m2repository
script:
- "./gradlew build connectedCheck"
env:
  global:
    #SWAD_APP_KEY
  - secure: qmkwdeZeZufS57yoXqeFD1WSXfCm8rdMEsjU1A44BVfklJikFdrc6ejqTzh4Kd56KhATYFT5cQmjJosT2QEf2hBQ77eLMAxEv+9XNioA7C8IHpHNnGx08egZBnwNM2uSr23MSws45+UAcVI1yDnpfBxD+IXFKS6Ms/ltd0/NYvjMhdTLF7ZOA6SX5uM8+o2F2SnhBOxsrdMOO3cK6mgI1eRoyqZKvL0fE+nE3ilTEX0TpReXsQtfA62EGi15Y2STbO7E0Yot7liFrF5FWrk/5C54nF581Aq2O69SVdVwVzENn3eHf2lbMdyCj8+arkBG19HZjYaUOHBDgvFudn/O03Ep2HR5h55Lj6Ns72lRxhPI84Lf6gP5l5sKEkkRB953ovTeYJ+WkbjcCFoSUp+dDVtUsIuiF2gzldtTc6KyEcCbxSgGzUIImRpbv60NvRkRXItgRmWvGdtCltAkn8160ITWNS3wFAZMWwk+NL1t+J6Q5YXJCOM4ldkTCHVtWnK73xK30wIPZm7Z9YIuBtaaLlNdDSZuk5qpxee2sfdx4VmE4AwapJt4GxPkyuJWUfX4tn/qbavR5zdYL8RkIAwkFq0WktebbsZqJCXEPTTWVprP3gv5sDIOgRxmGQC71fZf70jdUwLapmxPJxLbTFl5rRtevcbeommN3qWt1HKX/t8=
    #ANALYTICS_APP_KEY
  - secure: KKBRF69oXeRxfKcG10LG43PR0Ig3KIAAtyK5HvwP6J/OdiihzMRsdikaSRA4cDj/FjhQZGjU2ktMApbjtr5Qd6GjrLf3QRNZ+0ntuiAj7dfcaDf9HWZEvgQyco4xRbXcmQV7uM3g624Yf+8Cl5vSsuF20XJssq9C4hqinzNm5/suGO8BtALpzsy0mDtOQ6Q2b/2rGmwzp6TIuJEXKZlNELrr04lLZjWiBxbAONSXwEt1lhJiXVp4ovvfV9l0OQoBBEdON5CaviqZblB3Br3Lsw87MC993b6+1Ve7ac8aGic0IAHWWnOmUCRYhiMReuzgfsJIdsaysN4I9kALJOmHHxYraKOC1GgfM14/DVTZrwtyqorJeiXzi44208bEPfLsPv6SVOkIo0EfpDckoI2jfrfP30trOm6t8HLdY94a+9kyR0+uivLj39e+eDRRXkJ2zeluF4tejW/8R3y4wqXzJzSu+O1UCN5o+7o0SPR4UtXhvJYOURGpXORbN9IfYcbjkK7BcTPyAKOFPbGh7EYLJyLKlM1cD7BL0lW8eAkAeukZjLNrEiOE+tCLJL7205423UhCkBYuDLPE0eHerdovX7SypTSICmQX89WovrNle6/hACq7ndjJoNMDW5+pEugHDJDEXZPYlaRBYvVTZRXRTstBsRBQnGvOLhTxLj/LTVU=
before_install:
 - chmod +x gradlew