/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package es.ugr.swad.swadroid;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int erroricon=0x7f020000;
        public static final int swadroid=0x7f020001;
    }
    public static final class id {
        public static final int functionsList=0x7f070000;
        public static final int functions_menu=0x7f070001;
        public static final int login_menu=0x7f070002;
        public static final int preferences_menu=0x7f070003;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class menu {
        public static final int menu=0x7f060000;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int close_dialog=0x7f050003;
        public static final int errorMsgLaunchingActivity=0x7f050014;
        public static final int functionsTitle_menu=0x7f05000f;
        public static final int loginModuleLabel=0x7f050001;
        public static final int loginProgressDescription=0x7f050013;
        public static final int loginProgressTitle=0x7f050012;
        public static final int loginTitle_menu=0x7f050011;
        public static final int preferencesTitle_menu=0x7f050010;
        public static final int saveMsg_preferences=0x7f05000c;
        public static final int saveSummary_preferences=0x7f05000d;
        public static final int saveTitle_preferences=0x7f05000e;
        public static final int set_preferences=0x7f050004;
        public static final int title_error_dialog=0x7f050002;
        public static final int userIDName_preferences=0x7f050006;
        public static final int userIDSummary_preferences=0x7f050007;
        public static final int userIDTitle_preferences=0x7f050008;
        public static final int userPasswordName_preferences=0x7f050009;
        public static final int userPasswordSummary_preferences=0x7f05000a;
        public static final int userPasswordTitle_preferences=0x7f05000b;
        public static final int user_preferences=0x7f050005;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
