name: Android CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: List /home/runner/work/SWADroid/SWADroid/SWADroid/
      run: ls /home/runner/work/SWADroid/SWADroid/SWADroid/
    - name: Show /home/runner/work/SWADroid/SWADroid/SWADroid/build.gradle
      run: cat /home/runner/work/SWADroid/SWADroid/SWADroid/build.gradle
    - name: Build with Gradle
      run: ./gradlew build